{
 "title": "Cisco UCS C885A",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Power Usage (Watts)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(psu_power_watts)" }
   ]
  },
  {
   "title": "CPU Tray PSU Power Usage (Watts)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "psu_power_watts{psu_name=~\"CPU_TRAY_PSU.*\"}",
     "legendFormat": "{{psu_name}}"
    }
   ]
  },
  {
   "title": "GPU Tray PSU Power Usage (Watts)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "psu_power_watts{psu_name=~\"GPU_TRAY_PSU.*\"}",
     "legendFormat": "{{psu_name}}"
    }
   ]
  },
  {
   "title": "Total Power Usage (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "sum(psu_power_watts)" }
   ]
  },
  {
   "title": "CPU Tray PSU Power Usage (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "psu_power_watts{psu_name=~\"CPU_TRAY_PSU.*\"}",
     "legendFormat": "{{psu_name}}"
    }
   ]
  },
  {
   "title": "GPU Tray PSU Power Usage (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "psu_power_watts{psu_name=~\"GPU_TRAY_PSU.*\"}",
     "legendFormat": "{{psu_name}}"
    }
   ]
  },
  { "title": "GPU Tray FANs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN[1] (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN[2] (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN[3] (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN[4] (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  {
   "title": "All GPU Tray FAN Speeds (RPM)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 14, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN[1-8] (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN[5] (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN[6] (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN[7] (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN[8] (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  { "title": "CPU Tray FANs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN[9] (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN10 (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN11 (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN12 (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  {
   "title": "All CPU Tray FAN Speeds (RPM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN(9|1[0-2]) (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  { "title": "NVME Disks FANs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN13 (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN14 (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN15 (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN16 (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  {
   "title": "All NVME Disks FAN Speeds (RPM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "fan_speed_rpm{fan_name=~\"FAN1[3-6] (Front|Rear)\"}",
     "legendFormat": "{{fan_name}}"
    }
   ]
  },
  { "title": "Thermal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Temp GPU1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 22, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "temperature_celsius{sensor_name=~\"TEMP_GB_GPU[1-8]\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "Ambient Temperature (°C)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature_celsius{sensor_name=\"TEMP_AMBIENT\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "All GPU Temperatures (°C)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 4, "y": 73 },
   "targets": [
    {
     "expr": "temperature_celsius{sensor_name=~\"TEMP_GB_GPU[1-8]$\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "DIMMs Temperatures (°C)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "temperature_celsius{sensor_name=~\"TEMP_DIMM_ZONE.*\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "OCP Cards Temperatures (°C)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 80 },
   "targets": [
    {
     "expr": "temperature_celsius{sensor_name=~\"TEMP_OCP.*\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "HSC Temperatures (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "temperature_celsius{sensor_name=~\"TEMP_.*HSC.*\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "CEM Slots Temperatures (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 89 },
   "targets": [
    {
     "expr": "temperature_celsius{sensor_name=~\"TEMP_CEM.*\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "DCSCM Temperatures (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "temperature_celsius{sensor_name=~\"TEMP_DCSCM.*\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "FPGA Temperatures (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 97 },
   "targets": [
    {
     "expr": "temperature_celsius{sensor_name=~\"TEMP_GB_FPGA.*\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "INLET Temperatures (°C)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "temperature_celsius{sensor_name=~\"TEMP_GB_INLET.*\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "OUTLET Temperatures (°C)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 105 },
   "targets": [
    {
     "expr": "temperature_celsius{sensor_name=~\"TEMP_MB_OUTLET.*\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "PCB Temperatures (°C)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "temperature_celsius{sensor_name=~\"TEMP_GB_PCB.*\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "NVS Temperatures (°C)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 114 },
   "targets": [
    {
     "expr": "temperature_celsius{sensor_name=~\"TEMP_GB_NVS.*\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "HIB_PEX Temperatures (°C)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "temperature_celsius{sensor_name=~\"TEMP_HIB_PEX.*\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "PEX_SW Temperatures (°C)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 123 },
   "targets": [
    {
     "expr": "temperature_celsius{sensor_name=~\"TEMP_GB_PEX_SW.*\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "Midplane Temperatures (°C)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 132 },
   "targets": [
    {
     "expr": "temperature_celsius{sensor_name=~\"TEMP_MIDPLANE.*\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "RTM Temperatures (°C)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 132 },
   "targets": [
    {
     "expr": "temperature_celsius{sensor_name=~\"TEMP_GB_RTM.*\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  }
 ]
}